### ISSUE TITLE
Back reference and Problem 6

### ISSUE THREAD

**Issue by livibetter** [Liniarc/regexProgram#7]
I couldn't get past Problem 6 which requries the use of back reference `\#`, I think the code needs to be enbabled for [back references][bkref] (from 1.52 doc, the version I am using):

> `no_bk_refs`:  When set then backreferences are disabled. This bit is on by default for POSIX-Extended regular expressions, but can be unset to support for backreferences on.

[bkref]: http://www.boost.org/doc/libs/1_52_0/libs/regex/doc/html/boost_regex/ref/syntax_option_type/syntax_option_type_extended.html

I made the following change:

```diff
diff --git a/regex.cpp b/regex.cpp
index fd39b1b..8847690 100644
--- a/regex.cpp
+++ b/regex.cpp
@@ -289,7 +289,7 @@ void performRegex()
     {
         if (extended)
         {
-            r.assign(regexPattern.c_str(), regex::extended);
+            r.assign(regexPattern.c_str(), regex::extended & ~regex::no_bk_refs);
         }
         else
         {
```

It does work for me. I could confirm that with the first problem `(a)b\1` to see it matching "aba". I am not familiar with Boost or C++, not sure if this is the right fix, or I'd just submit a PR.

(Can we get an option for jumping to problem # or a key to skip a problem?)

**Comment by Liniarc** [comment]
I had originally designed the regex to help simulate how grep/egrep would function with the Posix basic/extended regex. Standard regex supports backrefs while extended Posix does not. As such I don't think adding backrefs to extended regex will be the best solution.

**Comment by livibetter** [comment]
@Liniarc I can understand that, and completely agree it should stick to the standards, however I don't get the backreferences in standard (exteneded option unchecked), either.

`(a)b\1` doesn't match first three letters of last entry "abacus" in `problem1`. That's why I tried to make it in extended.

Maybe there is some differences between Boost library versions?

My version is 1.52.0, 1.55.0 is the latest stable versionon Gentoo, but I don't want to update if not necessary.

**Comment by JelF** [comment]
@Liniarc May be it is reasonable to add a hint in problem 6? I mean, it could be solved only in case we have backreference support, and it is not trivial that backreferences are turned of in extended mode, but works in simple

**Comment by livibetter** [comment]
@JelF I don't have back references even in standard, the extended checkbox is unchecked.

**Comment by JelF** [comment]
@livibetter it seems i realy wanna to know problem 6 solution as it done by @Liniarc :)

**Comment by livibetter** [comment]
@JelF I believe this would work `\b(.).*\1\b`, if back references is working.

**Comment by Liniarc** [comment]
The way I solved it with standard Posix is `^\(.\).*\1$`
The parenthesis apparently need to be escaped to form capture groups. Otherwise they will match a literal parenthesis character. (I have no clue why. It doesn't make sense to me either) This is consistent with my test of `grep \(.\)\1`.

**Comment by JelF** [comment]
@Liniarc seems i used a good chance to know something new. Thanks a lot

**Comment by livibetter** [comment]
I am closing this since it's no bug, I need to re-read POSIX regex, I meant for the first time.

**Comment by zhanglintc** [comment]
`^\(.\).*\1$` can solve the problem but `\b(.).*\1\b` can't, it makes me confused... :joy:
